environment:
  matrix:
    - JAVA_HOME : C:\Program Files\Java\jdk1.7.0\
    - JAVA_HOME : C:\Program Files\Java\jdk1.8.0\
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

test_script:
  - mvn test

build: off
